### ISSUE TITLE
CSS is polluted when used with Tailwind CSS

### ISSUE THREAD

**Issue by angelofan** [philfung/add-to-homescreen#41]
CSS is polluted when used with [Tailwind CSS](https://tailwindcss.com/).

## Screenshot
![image](https://github.com/user-attachments/assets/278704bc-f322-41cb-ada8-939dca1efaed)

## Code
```html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no, viewport-fit=cover">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/philfung/add-to-homescreen@2.2/dist/add-to-homescreen.min.css">
    <script src="https://cdn.jsdelivr.net/gh/philfung/add-to-homescreen@2.2/dist/add-to-homescreen.min.js"></script>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<title>TitleofApp with Tailwind CSS</title>
<style>
    body {
        min-height: 100vh;
    }
</style>

<body>
    <div>
        <button id="addToHomeScreen" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">
            Add to Home Screen
        </button>
    </div>
    <script>
        document.getElementById('addToHomeScreen').addEventListener('click', function (event) {
            event.stopPropagation();
            window.AddToHomeScreenInstance = new window.AddToHomeScreen({
                appName: 'TitleOfApp',
                appIconUrl: 'https://cdn.jsdelivr.net/gh/philfung/add-to-homescreen@2.2/dist/assets/img/aardvark-logo.png',
                assetUrl: 'https://cdn.jsdelivr.net/gh/philfung/add-to-homescreen@2.2/dist/assets/img/',
                maxModalDisplayCount: -1
            });

            ret = window.AddToHomeScreenInstance.show('en');
        });
    </script>

</body>

</html>
```

**Comment by angelofan** [comment]
One of the solutions is to consider using [Shadow DOM](https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_shadow_DOM).

> An important aspect of custom elements is encapsulation, because a custom element, by definition, is a piece of reusable functionality: it might be dropped into any web page and be expected to work. So it's important that code running in the page should not be able to accidentally break a custom element by modifying its internal implementation. Shadow DOM enables you to attach a DOM tree to an element, and have the internals of this tree hidden from JavaScript and CSS running in the page.

**Comment by euhm** [comment]
Hey @angelofan, I'm curious how you fixed it or which workaround you took.

thanks!

**Comment by angelofan** [comment]
@euhm  Now I use [@khmyznikov/pwa-install](https://github.com/khmyznikov/pwa-install). Everything works well.

**Comment by philfung** [comment]
@angelofan @euhm apologies for the delay.  This Tailwind issue is fixed in https://github.com/philfung/add-to-homescreen/commit/ba1c2e517cf392ed67928daddcaea7c5cfa8c576
Please update [CDN link](https://github.com/philfung/add-to-homescreen/blob/main/README.md) to use [release 2.5](https://github.com/philfung/add-to-homescreen/releases/tag/2.5) and all should render correctly with Tailwind.
<img width="194" alt="Screenshot 2024-11-08 at 7 44 38 PM" src="https://github.com/user-attachments/assets/654ada93-c2d5-4d12-b764-ed3650a91eb0">
<img width="200" alt="Screenshot 2024-11-08 at 7 44 16 PM" src="https://github.com/user-attachments/assets/1046e5e5-2a88-44d2-9b05-eaba79450315">
<img width="1090" alt="Screenshot 2024-11-08 at 7 43 47 PM" src="https://github.com/user-attachments/assets/3b1e7c1c-daaf-4d09-8d8f-0187f51ff7f2">
<img width="794" alt="Screenshot 2024-11-08 at 7 43 41 PM" src="https://github.com/user-attachments/assets/dcd15c29-4aa6-48ba-ae08-cdc90bd27530">
